name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }} \
          --build-arg VERSION=${{ github.sha }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      - name: Trigger Render Deploy
        run: |
          echo "Triggering deploy..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Trigger Render Deploy with new image
        run: |
          echo "Triggering deploy with SHA..."

          curl -X PATCH https://node-app-latest-ou2v.onrender.com/srv-d7irio67r5hc73cdmkag \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "image": "docker.io/${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}"
            }'

      # 🔥 CRITICAL STEP (this is what you were missing)
      - name: Wait for new version to go live
        run: |
          echo "Waiting for new version..."

          for i in {1..20}
          do
            VERSION=$(curl -s https://node-app-latest-ou2v.onrender.com/version)

            echo "Current: $VERSION"

            if [[ "$VERSION" == *"${{ github.sha }}"* ]]; then
              echo "New version is live!"
              break
            fi

            echo "Still old version... retrying"
            sleep 5
          done

      # 🔥 REAL HEALTH CHECK
      - name: Health Check
        run: |
          echo "Checking health multiple times..."

          for i in 1 2 3 4 5
          do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://node-app-latest-ou2v.onrender.com/health)

            if [ "$STATUS" -ne 200 ]; then
              echo "Health check failed at attempt $i"
              exit 1
            fi

            echo "Attempt $i passed"
            sleep 5
          done

          echo "App is stable"