name: Build & Push Node App

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          echo "Building version ${{ github.run_number }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.run_number }} .

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.run_number }}

      - name: Show Deployment Version
        run: echo "Built and pushed version ${{ github.run_number }}"