name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }} \
          --build-arg VERSION=${{ github.sha }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      # ✅ Save currently running version (for rollback)
      - name: Save previous version
        run: |
          PREV_VERSION=$(curl -s https://node-app-latest-ou2v.onrender.com/version | awk '{print $3}')
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV
          echo "Previous version: $PREV_VERSION"

      # ✅ Deploy NEW SHA (ONLY this, no webhook)
      - name: Deploy using SHA image
        run: |
          echo "Deploying new version..."

          curl -X PATCH https://node-app-latest-ou2v.onrender.com/srv-d7irio67r5hc73cdmkag \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data-raw "{\"image\":\"docker.io/${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}\"}"

      # ✅ Wait until NEW version is live
      - name: Wait for new version to go live
        run: |
          echo "Waiting for new version..."

          for i in {1..20}
          do
            VERSION=$(curl -s https://node-app-latest-ou2v.onrender.com/version)

            echo "Current: $VERSION"

            if [[ "$VERSION" == *"${{ github.sha }}"* ]]; then
              echo "New version is live!"
              break
            fi

            echo "Still old version... retrying"
            sleep 5
          done

      # ✅ HEALTH CHECK + AUTO ROLLBACK
      - name: Health Check & Auto Rollback
        run: |
          echo "Checking health..."

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://node-app-latest-ou2v.onrender.com/health)

          if [ "$STATUS" -ne 200 ]; then
            echo "Health check failed! Rolling back..."

            curl -X PATCH https://api.render.com/v1/services/srv-d7irio67r5hc73cdmkag \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              -H "Content-Type: application/json" \
              --data-raw "{\"image\":\"docker.io/${{ secrets.DOCKER_USERNAME }}/node-app:${PREV_VERSION}\"}"

            echo "Rollback triggered to version: $PREV_VERSION"
            exit 1
          else
            echo "App is healthy ✅"
          fi